# Generated by Django 5.1.3 on 2024-11-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba_panzofi_backend', '0002_admin_user_delete_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='button1_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='button2_count',
            field=models.IntegerField(),
        ),
    ]
