# Generated by Django 5.1.3 on 2024-11-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba_panzofi_backend', '0003_user_time_alter_user_button1_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('url_image', models.CharField(max_length=1000)),
            ],
        ),
    ]
