# Generated by Django 5.1.3 on 2024-11-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba_panzofi_backend', '0004_app'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('url_image', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='App',
        ),
    ]
